name: CI 6.0.44-TT

on:
  push:
    branches:
      - tomcat-6.0.44-TT
  pull_request:
    branches:
      - tomcat-6.0.44-TT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup jdk 6
      uses: actions/setup-java@v1
      with:
        java-version: '6'
    
    - name: donwload ant 9
      run: curl https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.9-bin.zip --output ant9.zip

    - name: unzip ant 9
      run: unzip -qq ant9.zip

    - name: downgrate ant version to 1.9.9
      run:  sudo cp -a apache-ant-1.9.9/. $ANT_HOME

    - name: download libraries
      run: curl https://support-delivery.s3.amazonaws.com/tomcat6-build-libs-.zip --output tomcat6-build-libs-.zip
      
    - name: extract libs
      run: unzip -qq tomcat6-build-libs-.zip -d /home/runner/
    
    - name: ant_build
      run: ant

    - name: ant_test
      run: ant test | true
      env:
          ANT_OPTS: -Xmx2G -XX:MaxPermSize=512m

    - name: obtained_error_result
      run: grep 'Caused an ERROR' output/build/logs/* > error_result.txt | true
      
    - name: obtained_failed_result
      run: grep 'FAILED' output/build/logs/* > failed_result.txt | true
    
    - name: print_error
      run: cat error_result.txt
      
    - name: print_failed
      run: cat failed_result.txt 
 
    - name: expected_error_and_failed_result
      run: touch known_errors.txt && touch known_failed.txt

#Known ERRORS   
    - name: remove_known_error_1
      run: sed -i.bak '/TEST-org.apache.catalina.tribes.group.interceptors.TestNonBlockingCoordinator.BIO.txt/d' error_result.txt | true

    - name: remove_known_error_2
      run: sed -i.bak '/TEST-org.apache.catalina.tribes.group.interceptors.TestNonBlockingCoordinator.NIO.txt/d' error_result.txt | true
      
    - name: remove_known_error_3
      run: sed -i.bak '/TEST-org.apache.coyote.http11.filters.TestFlushableGZIPOutputStream.BIO.txt/d' error_result.txt | true

    - name: remove_known_error_4
      run: sed -i.bak '/TEST-org.apache.coyote.http11.filters.TestFlushableGZIPOutputStream.NIO.txt/d' error_result.txt | true      

#Known FAILED
    - name: remove_known_failed_1
      run: sed -i.bak '/TEST-org.apache.coyote.http11.TestInternalInputBuffer.NIO.txt/d' failed_result.txt | true

    - name: remove_known_failed_2
      run: sed -i.bak '/TEST-org.apache.catalina.tribes.group.TestGroupChannelMemberArrival.NIO.txt/d' failed_result.txt | true
      
    - name: remove_known_failed_3
      run: sed -i.bak '/TEST-org.apache.catalina.tribes.group.interceptors.TestOrderInterceptor.NIO.txt/d' failed_result.txt | true

    - name: remove_known_failed_4
      run: sed -i.bak '/TEST-org.apache.catalina.tribes.group.interceptors.TestNonBlockingCoordinator.NIO.txt/d' failed_result.txt | true
      
    - name: remove_known_failed_5
      run: sed -i.bak '/TEST-org.apache.catalina.tribes.group.TestGroupChannelMemberArrival.BIO.txt/d' failed_result.txt | true      
 
    - name: remove_known_failed_6
      run: sed -i.bak '/TEST-org.apache.catalina.tribes.group.interceptors.TestNonBlockingCoordinator.BIO.txt/d' failed_result.txt | true
  
    - name: remove_known_failed_7
      run: sed -i.bak '/TEST-org.apache.catalina.core.TestApplicationHttpRequest/d' failed_result.txt | true

    - name: remove_known_failed_8
      run: sed -i.bak '/TEST-org.apache.catalina.servlets.TestDefaultServlet/d' failed_result.txt | true  

    - name: remove_known_failed_9
      run: sed -i.bak '/TEST-org.apache.catalina.servlets.TestDefaultServletIfMatchRequests/d' failed_result.txt | true
    
    - name: final_status
      run: diff failed_result.txt known_failed.txt && diff error_result.txt known_errors.txt
      
     
